### ISSUE TITLE
CityAirRequest constructor fails with KeyError.

### ISSUE THREAD

**Issue by d1mach** [cityairllc/cityair_python_api#2]
CityAirRequest constructor fails with an exception `KeyError: 'SerialNumber'`.

This happens when API user has access only to station data and does not have access to individual devices via the low-level Device API. For such users `get_devices` fails as the list of devices is empty.

**Comment by d1mach** [comment]
```
Traceback (most recent call last):

  File "/home/ubuntu/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py",
line 3063, in get_loc

    return self._engine.get_loc(key)

  File "pandas/_libs/index.pyx", line 140, in
pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in
pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in
pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'SerialNumber'

```

**Comment by d1mach** [comment]
Reproducible with cityair-api-0.1.10 installed from PyPi when the user has Observer access level. Upgrading access level to Operator resolves the problem.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dimch/.local/lib/python3.6/site-packages/cityair_api/request.py", line 36, in __init__
    self.device_serials = self.get_devices(format='series')
  File "/home/dimch/.local/lib/python3.6/site-packages/cityair_api/request.py", line 76, in get_devices
    df.index = df['SerialNumber']
  File "/home/dimch/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2975, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/dimch/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2892, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'SerialNumber'
```
